## Bài 1. Tạo Tensor cơ bản
Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

Yêu cầu: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

In [3]:
import torch
a = torch.tensor(
    [[1,2,3],
     [4,5,6]],
     dtype = torch.int32
)
print(a)
print("kich thuoc",a.shape)
print("so chieu",a.ndim)
print("kieu du lieu",a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
kich thuoc torch.Size([2, 3])
so chieu 2
kieu du lieu torch.int32


## Bài 2. Tạo các Tensor thường dùng
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

Yêu cầu:

• Nhận xét sự khác nhau giữa torch.rand() và torch.randn().

• Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

Nhận xét rand() và randn()

rand()
tạo tensor gồm các số ngẫu nhiên từ 0 đến 1(phân phối đều)

randn() 
tạo tensor gồm các số ngẫu nhiên theo phân phối chuẩn, có thể xuất hiện số âm

In [6]:
import torch

a = torch.rand(3,4)
b = torch.randn(3,4)
c = torch.zeros(2,4)
d = torch.ones(2,4)
e = torch.eye(4)
f = torch.full((5,5),10)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

tensor([[0.7293, 0.8684, 0.3117, 0.3624],
        [0.0329, 0.3715, 0.6111, 0.9013],
        [0.2151, 0.6876, 0.9856, 0.0771]])
tensor([[-0.9659,  0.1279, -0.7522, -0.9979],
        [ 0.3959, -0.4031, -0.8461, -0.5122],
        [-0.9212, -0.7459, -0.5812, -0.9343]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3. Kiểm tra thông tin Tensor
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

Yêu cầu: Giải thích ý nghĩa của torch.Size([2, 3, 4]).

torch.Size([2, 3, 4]) cho biết Tensor có 3 chiều, với kích thước lần lượt là 2, 3 và 4. Có thể hiểu Tensor gồm 2 ma trận, mỗi ma trận có 3 hàng và 4 cột, tổng cộng có 24 phần tử.

In [ ]:
import torch
a = torch.zeros(2,3,4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

## Bài 4. Slicing và Indexing
Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

Yêu cầu:

• Cho biết shape của a[1] và a[1:, 2:4].

• Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

a[1] -> (4,5)

a[1:, 2:4] -> (2,2,5)

In [ ]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

b = torch.randn(3,4,5)
print(b[1].shape)
print(b[1:,2:4].shape)
print("Hai phan tu cuoi cung tren chieu thu ba")
print(b[:, :, -2:])


Original tensor:
tensor([[[-0.4406,  1.0175,  1.5045, -1.7270, -0.5305],
         [ 2.2858,  0.5697, -1.9880, -0.1102, -1.4019],
         [-0.4108, -0.2421,  0.7018,  1.6925, -0.2750],
         [ 0.3854, -0.9148,  0.5352, -0.0121,  0.3369]],

        [[ 1.0124,  0.4664,  0.2557,  1.6949, -0.7845],
         [ 0.3218, -0.4449, -1.2687, -0.9006, -0.3704],
         [ 1.1448, -0.6422, -0.0871, -1.0753, -1.8819],
         [-0.6943, -0.4263,  1.2122,  1.0079, -0.3797]],

        [[ 0.2387, -1.8704, -0.8993, -1.2793, -0.4430],
         [ 1.9101, -1.7121,  0.5045, -0.4465, -0.2676],
         [-0.0615,  0.4740,  0.2724,  0.8196,  0.4663],
         [-0.1507,  1.5286,  1.2732,  1.1038,  0.1338]]])

Tensor a[1]:
tensor([[ 1.0124,  0.4664,  0.2557,  1.6949, -0.7845],
        [ 0.3218, -0.4449, -1.2687, -0.9006, -0.3704],
        [ 1.1448, -0.6422, -0.0871, -1.0753, -1.8819],
        [-0.6943, -0.4263,  1.2122,  1.0079, -0.3797]])

Tensor a[1:, 2:4]:
tensor([[[ 1.1448, -0.6422, -0.0871, -1.0753, -1.8

## Bài 5. Reshape và Flatten
Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

Yêu cầu:

• Kiểm tra số phần tử trước và sau khi reshape.

• Thử reshape Tensor thành kích thước 2 × 6.

In [2]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))
print("\nso phan tu truoc rasphape")
print(a.numel())
print("\nso phan tu sau rasphape")
print(a.reshape(3 ,2, 2).numel())
print("\nresphape to 2 x 6")
print(a.reshape(2,6))

Original:
tensor([[ 0.2268, -0.2697, -0.2641,  0.0153],
        [ 0.6660, -1.0213,  0.3034,  1.5549],
        [-0.9917,  0.2557, -1.7216, -0.3852]])

Flatten:
tensor([ 0.2268, -0.2697, -0.2641,  0.0153,  0.6660, -1.0213,  0.3034,  1.5549,
        -0.9917,  0.2557, -1.7216, -0.3852])

Reshape to 3 x 2 x 2:
tensor([[[ 0.2268, -0.2697],
         [-0.2641,  0.0153]],

        [[ 0.6660, -1.0213],
         [ 0.3034,  1.5549]],

        [[-0.9917,  0.2557],
         [-1.7216, -0.3852]]])

so phan tu truoc rasphape
12

so phan tu sau rasphape
12

resphape to 2 x 6
tensor([[ 0.2268, -0.2697, -0.2641,  0.0153,  0.6660, -1.0213],
        [ 0.3034,  1.5549, -0.9917,  0.2557, -1.7216, -0.3852]])


## Bài 6. Phép toán và nhân ma trận
Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

Yêu cầu:

• Phân biệt phép toán a * b với a @ b.T.

• Cho biết shape của kết quả a @ b.T. 

a * b : nhân từng phần tử tương ứng

a @ b.T : phép nhân ma trận 

In [3]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)
print((a @ b.T).shape)

a:
tensor([[-0.3540,  0.4193,  0.3286],
        [-0.7494,  0.9218, -0.7147]])
b:
tensor([[ 0.5817, -0.8122,  0.1805],
        [ 0.9847,  1.7176,  1.3218]])

a + b:
tensor([[ 0.2277, -0.3929,  0.5091],
        [ 0.2352,  2.6394,  0.6071]])

a / b:
tensor([[-0.6086, -0.5162,  1.8203],
        [-0.7611,  0.5367, -0.5407]])

a^2:
tensor([[0.1253, 0.1758, 0.1080],
        [0.5617, 0.8497, 0.5108]])

Matrix multiplication:
tensor([[-0.4872,  0.8060],
        [-1.3137, -0.0994]])
torch.Size([2, 2])


## Bài 7. Các hàm thống kê trên Tensor
Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

Yêu cầu:

• Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.

dim=0 đi theo chiều dọc tính theo cột
dim=1 đi theo chiều ngang tính theo hàng

In [2]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 1.4804,  0.3835, -0.7060,  1.3966],
        [ 1.8175,  0.6645,  0.9795, -1.4960],
        [ 0.2967,  0.8329,  0.6598,  0.6604]])

Mean:
tensor([0.6386, 0.4914, 0.6125])

Standard deviation:
tensor([1.0257, 1.4115, 0.2257])

Cumulative sum:
tensor([[1.4804, 1.8639, 1.1579, 2.5545],
        [1.8175, 2.4820, 3.4615, 1.9654],
        [0.2967, 1.1296, 1.7895, 2.4498]])


## Bài 8. Autograd cơ bản
Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

Yêu cầu:

• Tính thủ công đạo hàm của y = x2 tại x = 3.6 và so sánh với x.grad.

• Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

tính thủ công = 7.2, tính x.grad = 7.2 => PyTorch autograd tính gradient chính xác

thay đổi hàm y thủ công bằng 23.6 , tính x.grad = 23.6 => PyTorch autograd tính gradient chính xác



In [4]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = 3*x**2 + 2*x + 1
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


## Bài 9. Gradient Descent tìm hệ số đa thức
Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

Yêu cầu:

• So sánh ba hệ số học được với [1, 2, 3].

• Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().

đúng với ba hệ số của đa thức ban đầu y = x² + 2x + 3.

Trong quá trình Gradient Descent, optimizer.zero_grad() dùng để xóa gradient của lần lặp trước, mse.backward() tính gradient tự động bằng Autograd, còn optimizer.step() cập nhật các hệ số w dựa trên gradient

In [6]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-1.4665],
        [-0.1963],
        [-0.0798]], requires_grad=True)
Learned coefficients:
tensor([[1.0075],
        [2.0097],
        [2.4923]], requires_grad=True)


## Bài 10. Giải hệ phương trình bằng Autograd
Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

Yêu cầu:

• Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.

• Nhận xét vì sao bài toán có thể có nhiều nghiệm.

Sử dụng Autograd và NAdam, ta tìm được nghiệm thỏa mãn gần đúng cả 4 phương trình. Hệ có vô số nghiệm vì chỉ có 3 phương trình độc lập cho 4 ẩn.

In [8]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.5338, requires_grad=True)
B = tensor(4.4662, requires_grad=True)
C = tensor(3.4662, requires_grad=True)
D = tensor(2.4662, requires_grad=True)


## Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:
• Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

• Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

• Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

• Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.