## Bài 1. Tạo Tensor cơ bản
Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [3]:
import torch
a = torch.tensor(
    [[1,2,3],
     [4,5,6]],
     dtype = torch.int32
)
print(a)
print("kich thuoc",a.shape)
print("so chieu",a.ndim)
print("kieu du lieu",a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
kich thuoc torch.Size([2, 3])
so chieu 2
kieu du lieu torch.int32


## Bài 2. Tạo các Tensor thường dùng
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

Nhận xét rand() và randn()

rand()
tạo tensor gồm các số ngẫu nhiên từ 0 đến 1(phân phối đều)

randn() 
tạo tensor gồm các số ngẫu nhiên theo phân phối chuẩn, có thể xuất hiện số âm

In [6]:
import torch

a = torch.rand(3,4)
b = torch.randn(3,4)
c = torch.zeros(2,4)
d = torch.ones(2,4)
e = torch.eye(4)
f = torch.full((5,5),10)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

tensor([[0.7293, 0.8684, 0.3117, 0.3624],
        [0.0329, 0.3715, 0.6111, 0.9013],
        [0.2151, 0.6876, 0.9856, 0.0771]])
tensor([[-0.9659,  0.1279, -0.7522, -0.9979],
        [ 0.3959, -0.4031, -0.8461, -0.5122],
        [-0.9212, -0.7459, -0.5812, -0.9343]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3. Kiểm tra thông tin Tensor
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

torch.Size([2, 3, 4]) cho biết Tensor có 3 chiều, với kích thước lần lượt là 2, 3 và 4. Có thể hiểu Tensor gồm 2 ma trận, mỗi ma trận có 3 hàng và 4 cột, tổng cộng có 24 phần tử.

In [ ]:
import torch
a = torch.zeros(2,3,4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

## Bài 4. Slicing và Indexing
Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

a[1] -> (4,5)

a[1:, 2:4] -> (2,2,5)

In [ ]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

b = torch.randn(3,4,5)
print(b[1].shape)
print(b[1:,2:4].shape)
print("Hai phan tu cuoi cung tren chieu thu ba")
print(b[:, :, -2:])


Original tensor:
tensor([[[-0.4406,  1.0175,  1.5045, -1.7270, -0.5305],
         [ 2.2858,  0.5697, -1.9880, -0.1102, -1.4019],
         [-0.4108, -0.2421,  0.7018,  1.6925, -0.2750],
         [ 0.3854, -0.9148,  0.5352, -0.0121,  0.3369]],

        [[ 1.0124,  0.4664,  0.2557,  1.6949, -0.7845],
         [ 0.3218, -0.4449, -1.2687, -0.9006, -0.3704],
         [ 1.1448, -0.6422, -0.0871, -1.0753, -1.8819],
         [-0.6943, -0.4263,  1.2122,  1.0079, -0.3797]],

        [[ 0.2387, -1.8704, -0.8993, -1.2793, -0.4430],
         [ 1.9101, -1.7121,  0.5045, -0.4465, -0.2676],
         [-0.0615,  0.4740,  0.2724,  0.8196,  0.4663],
         [-0.1507,  1.5286,  1.2732,  1.1038,  0.1338]]])

Tensor a[1]:
tensor([[ 1.0124,  0.4664,  0.2557,  1.6949, -0.7845],
        [ 0.3218, -0.4449, -1.2687, -0.9006, -0.3704],
        [ 1.1448, -0.6422, -0.0871, -1.0753, -1.8819],
        [-0.6943, -0.4263,  1.2122,  1.0079, -0.3797]])

Tensor a[1:, 2:4]:
tensor([[[ 1.1448, -0.6422, -0.0871, -1.0753, -1.8

## Bài 5. Reshape và Flatten
Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.